#!/usr/bin/python3
"""
zram_setup.py – Automatic ZRAM compressed-swap configuration for installer hooks.

During OS installation (Ubiquity or Calamares) this module is called to write a
persistent, production-grade ZRAM configuration onto the target filesystem so
that the installed system boots with ZRAM swap already configured—without any
post-install manual step.

RAM detection:
    Reads ``MemTotal`` from ``/proc/meminfo`` on the live (installer) system.

Dynamic ZRAM sizing formula:
    RAM ≤ 4096 MiB  →  ZRAM size = RAM × 2
    RAM ≤ 8192 MiB  →  ZRAM size = RAM × 1  (implies RAM > 4096 MiB)
    RAM >  8192 MiB →  ZRAM size = RAM × 0.5  (rounded up)

Output:
    Writes ``/etc/systemd/zram-generator.conf`` inside the target root using
    the ``systemd-zram-generator`` INI format.
"""

import logging
import math
import os

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Default path to the live-system's memory information file.
_DEFAULT_MEMINFO = "/proc/meminfo"

#: Destination path of the config file, relative to the target root.
_CONF_REL_PATH = "etc/systemd/zram-generator.conf"

#: RAM threshold in MiB: at or below this value the ×2 multiplier is used.
_THRESHOLD_LOW_MB = 4096

#: RAM threshold in MiB: at or below this value (but above LOW) the ×1
#: multiplier is used; above this threshold the ×0.5 multiplier is used.
_THRESHOLD_MID_MB = 8192

# ---------------------------------------------------------------------------
# RAM detection
# ---------------------------------------------------------------------------


def read_mem_total_mb(proc_meminfo_path=_DEFAULT_MEMINFO):
    """Return total physical RAM in MiB by parsing *proc_meminfo_path*.

    Raises ``OSError`` when the file cannot be opened, and ``ValueError``
    when the ``MemTotal`` line is absent or malformed.
    """
    with open(proc_meminfo_path, "r", encoding="ascii") as fh:
        for line in fh:
            if line.startswith("MemTotal:"):
                # Format: "MemTotal:       16374252 kB"
                parts = line.split()
                if len(parts) < 2:
                    raise ValueError(
                        "Malformed MemTotal line in {!r}: {!r}".format(
                            proc_meminfo_path, line
                        )
                    )
                kb = int(parts[1])
                return kb // 1024
    raise ValueError(
        "MemTotal not found in {!r}".format(proc_meminfo_path)
    )


# ---------------------------------------------------------------------------
# ZRAM size calculation
# ---------------------------------------------------------------------------


def calc_zram_size_mb(ram_mb):
    """Return the recommended ZRAM swap size in MiB for *ram_mb* of physical RAM.

    Implements the adaptive sizing formula:

    * ``ram_mb ≤ 4096``  →  ``ram_mb × 2``
    * ``ram_mb ≤ 8192``  →  ``ram_mb × 1``   (implies ``ram_mb > 4096``)
    * ``ram_mb >  8192`` →  ``math.ceil(ram_mb × 0.5)``

    Raises ``ValueError`` for non-positive *ram_mb*.
    """
    if ram_mb <= 0:
        raise ValueError(
            "ram_mb must be a positive integer, got {!r}".format(ram_mb)
        )
    if ram_mb <= _THRESHOLD_LOW_MB:
        return ram_mb * 2
    if ram_mb <= _THRESHOLD_MID_MB:
        return ram_mb
    return math.ceil(ram_mb * 0.5)


# ---------------------------------------------------------------------------
# Config file generation
# ---------------------------------------------------------------------------


def generate_zram_conf(zram_size_mb):
    """Return the ``zram-generator.conf`` INI content for *zram_size_mb*.

    The returned string is suitable for writing directly to
    ``/etc/systemd/zram-generator.conf`` on the target system.
    """
    return (
        "# Automatically generated by cinnamon-zram-setup during OS installation.\n"
        "# See zram-generator.conf(5) for documentation.\n"
        "\n"
        "[zram0]\n"
        "zram-size = {size}\n"
        "compression-algorithm = zstd\n"
    ).format(size=zram_size_mb)


# ---------------------------------------------------------------------------
# Main installer action
# ---------------------------------------------------------------------------


def install_zram_conf(target_root, proc_meminfo_path=_DEFAULT_MEMINFO):
    """Detect RAM, calculate ZRAM size, and write the config into *target_root*.

    *target_root* is the path under which the installed system's filesystem is
    mounted — typically ``/target`` for Ubiquity or the Calamares root mount.

    The function creates ``<target_root>/etc/systemd/`` if it does not exist,
    then writes ``zram-generator.conf`` there.

    Returns the absolute path of the written configuration file.
    Raises ``OSError`` or ``ValueError`` on failure.
    """
    ram_mb = read_mem_total_mb(proc_meminfo_path)
    zram_mb = calc_zram_size_mb(ram_mb)
    log.info(
        "install_zram_conf: RAM=%d MiB, ZRAM=%d MiB, target=%r",
        ram_mb,
        zram_mb,
        target_root,
    )

    conf_path = os.path.join(target_root, _CONF_REL_PATH)
    os.makedirs(os.path.dirname(conf_path), mode=0o755, exist_ok=True)

    content = generate_zram_conf(zram_mb)
    with open(conf_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    log.info("install_zram_conf: wrote %r", conf_path)
    return conf_path
